[build]
  command = "npm install --prefix frontend && npm run build --prefix frontend"
  publish = "frontend/dist"

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Embedder-Policy = "unsafe-none"
