export const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://localhost:5000";

export const ENDPOINTS = {
  BASE_URL: API_BASE_URL,
  GENERATE: `${API_BASE_URL}/api/generate`,
  REPORTS: `${API_BASE_URL}/api/reports/`,
  STATS: `${API_BASE_URL}/api/reports/stats`,
  SUGGEST: `${API_BASE_URL}/api/suggest`,
  AI_DESCRIBE: `${API_BASE_URL}/api/ai-describe`,
  AUTH: {
    LOGIN: `${API_BASE_URL}/api/auth/login`,
    SIGNUP: `${API_BASE_URL}/api/auth/signup`,
    GOOGLE: `${API_BASE_URL}/api/auth/google`,
    FORGOT_PASSWORD: `${API_BASE_URL}/api/auth/forgot-password`,
    RESET_PASSWORD: `${API_BASE_URL}/api/auth/reset-password`,
    ME: `${API_BASE_URL}/api/auth/me`,
    UPDATE_PROFILE: `${API_BASE_URL}/api/auth/update-profile`,
  },
  FILES: {
    UPLOAD: `${API_BASE_URL}/api/files/upload`,
    GET: (key) => `${API_BASE_URL}/api/files/${encodeURIComponent(key)}`,
    UPDATE: `${API_BASE_URL}/api/files/update`,
    DELETE: `${API_BASE_URL}/api/files/delete`,
  },
  HEALTH: `${API_BASE_URL}/`,
  FACTORY_AUDIT: {
    BASE: `${API_BASE_URL}/api/factory-audit`,
    BY_ID: (id) => `${API_BASE_URL}/api/factory-audit/${encodeURIComponent(id)}`,
    GENERATE: (id, format = "docx") => `${API_BASE_URL}/api/factory-audit/${encodeURIComponent(id)}/generate?format=${encodeURIComponent(format)}`,
    SUBMIT: (id) => `${API_BASE_URL}/api/factory-audit/${encodeURIComponent(id)}/submit`,
  },
  INSPECTOR: {
    SUMMARY: `${API_BASE_URL}/api/inspector/dashboard/summary`,
    TASKS: `${API_BASE_URL}/api/inspector/tasks`,
    TASK_BY_ID: (id) => `${API_BASE_URL}/api/inspector/tasks/${id}`,
    ACCEPT_TASK: (id) => `${API_BASE_URL}/api/inspector/tasks/${id}/accept`,
    NOTIFICATIONS: `${API_BASE_URL}/api/inspector/notifications`,
    READ_NOTIFICATION: (id) => `${API_BASE_URL}/api/inspector/notifications/${id}/read`,
    READ_ALL_NOTIFICATIONS: `${API_BASE_URL}/api/inspector/notifications/read-all`,
  },
  MANAGER: {
    QUEUE: `${API_BASE_URL}/api/manager/queue`,
    REPORT_DETAILS: (id) => `${API_BASE_URL}/api/manager/reports/${id}`,
    UPDATE_STATUS: (id) => `${API_BASE_URL}/api/manager/reports/${id}/status`,
    SUBMIT_FEEDBACK: (id) => `${API_BASE_URL}/api/manager/reports/${id}/correction`,
    FINALIZE: (id) => `${API_BASE_URL}/api/manager/reports/${id}/finalize`,
    ADD_REMARK: (id) => `${API_BASE_URL}/api/manager/reports/${id}/remarks`,
  },
  ONBOARDING: {
    STATUS:         `${API_BASE_URL}/api/inspector/onboarding/status`,
    COMPLETE_STEP:  `${API_BASE_URL}/api/inspector/onboarding/complete-step`,
    VIDEO_PROGRESS: `${API_BASE_URL}/api/inspector/onboarding/video-progress`,
    QUESTIONS:      `${API_BASE_URL}/api/inspector/onboarding/assessment-questions`,
    SUBMIT:         `${API_BASE_URL}/api/inspector/onboarding/submit-assessment`,
  },
  ADMIN: {
    INSPECTORS: `${API_BASE_URL}/api/admin/inspectors`,
  },
  NOTIFICATIONS: {
    MY: `${API_BASE_URL}/api/notifications/my-notifications`,
    BELL_COUNT: `${API_BASE_URL}/api/notifications/bell-count`,
    MARK_READ: `${API_BASE_URL}/api/notifications/mark-read`,
    MARK_ALL_READ: `${API_BASE_URL}/api/notifications/mark-all-read`,
    ALL: `${API_BASE_URL}/api/notifications/all`,
    CREATE: `${API_BASE_URL}/api/notifications/create`,
    UPDATE: (id) => `${API_BASE_URL}/api/notifications/${encodeURIComponent(id)}`,
    DELETE: (id) => `${API_BASE_URL}/api/notifications/${encodeURIComponent(id)}`,
  },
  EMAILS: {
    LIST: `${API_BASE_URL}/api/emails`,
    RETRY: (id) => `${API_BASE_URL}/api/emails/${encodeURIComponent(id)}/retry`,
    TEST: `${API_BASE_URL}/api/emails/test`,
  },
};
